### ISSUE TITLE
How can I turn off "templateInterpolationService"?

### ISSUE THREAD

**Issue by khalidchawtany** [neoclide/coc-vetur#14]
I get lots of errors, while there is nothing wrong with my code. How can I disable "templateInterpolationService"

![Screen Shot 2019-08-19 at 4 36 29 PM](https://user-images.githubusercontent.com/1681606/63270535-0a4f4080-c2a1-11e9-8cb8-204bc5f783e0.png)

**Comment by chemzqm** [comment]
You can't turn off a specific diagnostic with coc.nvim, submit your issue to https://github.com/vuejs/vetur

**Comment by khalidchawtany** [comment]
it is already possible
(https://github.com/vuejs/vetur/issues/1242#issuecomment-486614490)
 to turn it off. However, I have no Idea where/how to send that config option from coc.

**Comment by chemzqm** [comment]
vetur's bug, it should be fales by default.
