### ISSUE TITLE
Errors show up delayed, only after first write

### ISSUE THREAD

**Issue by doits** [neoclide/coc-vetur#20]
I noticed a new strange behavior that it will only display errors after first write. So when I open a file no error is displayed until I do a `:w`. Then it shoes up instantly. *And* I have to wait some seconds, probably because the linter boots up. If I hit `:w` too early, no errors are displayed (and will not until I hit `:w` again).

This all started after updating `@vue/eslint-config-typescript` to `5.0.0` and with it  `@typescript-eslint/parser` to  `2.7.0`.

**Comment by doits** [comment]
Actually I think my coc-vetur just broke and maybe that is the problem why I am missing all the type annotation :-) Debugging to see what is going on ...

**Comment by doits** [comment]
@chemzqm I just updated the title if this issue because it was misleading and added some info about my problems ... `coc-vetur` seems to be broken for me and I'm not sure how to debug this and provide more info.

**Comment by doits** [comment]
@chemzqm I again found it to be a much simpler issue ... sorry for the mess, but I still don't know why it behaves llike this.

**Comment by chemzqm** [comment]
Probably we can't do anything.

**Comment by doits** [comment]
I'm just guessing but maybe this is happening:

1. When opening  a file, the language server starts up and this takes some time (lets say 2-4 seconds)
2. coc-vetur asks to lint the file but the language server is not ready, so it does not return any errors
3. the language server gets ready
4. on save the file is linted again, now the language  server is ready and it returns the errors

Can this be  the case? Or do you think there is something different happening?

I don't know any internals about coc or coc-vetur so I'm not sure if this is what might happen or coc works differently. Maybe you can give an educated guess and then I can take a look at the code to see if there is anything we can do.

**Comment by chemzqm** [comment]
Should be problem of your vetur, I don't know anything about the detail.

**Comment by doits** [comment]
Can you please test if you too have the problem? If not, then maybe my local vim config is the problem.

I just uploaded an example project at https://github.com/doits/vue-delay-bug. Can you please clone it and simply open `src/App.vue` in vim.

For me it has the mentioned behavior of not displaying the linting error (wrong return in `methods`) directly after opening the file, but only after I save the file after waiting 1-2 seconds.

Is it like this for you too?

**Comment by chemzqm** [comment]
I don't have any issue with your project, so no idea. 
Try minimal vimrc instead.

**Comment by doits** [comment]
Alright, thanks for testing, then it must be something with my config ... I'll see if I find this out, but it is no problem with coc-vetur then.
