### ISSUE TITLE
vetur 2307 cannot find module @/api/xxx

### ISSUE THREAD

**Issue by IndexXuan** [neoclide/coc-vetur#21]
正确配置了 webpack alias in vue.config.js & tsconfig.js#paths，为什么还是提示找不到这种类似 alias 引用的依赖 ~ VSCode 可以，求大神帮忙看看 ~ 万分感激 ！

**Comment by IndexXuan** [comment]
在 coc-settings.json 中设置了 rootPatterns 包含 vue.config.js，可是 tsconfig.js 还是会找到根目录而不是 vue 项目所在的子目录的 tsconfig.js。希望大神可以支持 tsconfig.js 的正确定位 ~

**Comment by chemzqm** [comment]
重现不了，我不写 vue

**Comment by chemzqm** [comment]
可能是你 workspaceFolder 错了 https://github.com/neoclide/coc.nvim/wiki/Using-workspaceFolders

**Comment by IndexXuan** [comment]
嗯嗯，不过看起来问题是 coc-vetur 比 VSCode 相比，不能就近定位 tsconfig.json，而是定位到了根目录。workspaceFolder 有什么办法验证码，我已经配置了 vue.config.js，定位到子目录

**Comment by IndexXuan** [comment]
我错了，大佬。应该是好的。抱歉打扰
