### ISSUE TITLE
Export `vetur.completion.scaffoldSnippetSources.*` options for use in `coc-settings.json`

### ISSUE THREAD

**Issue by seletskiy** [neoclide/coc-vetur#23]
`coc-vetur` version: **1.1.7** (8c55c4b)

It seems that vetur [uses emoji][1] to display completion item type. I use console `nvim` and font I use doesn't support emoji.

As a result, I see missing character glyph instead of actual icon:

<img  src="https://user-images.githubusercontent.com/674812/71968999-eae88e00-3216-11ea-97ec-adbf8470901a.png">

I found a workaround to specify [`vetur.completion.scaffoldSnippetSources.vetur`][2] in `coc-settings.json`:

<img src="https://user-images.githubusercontent.com/674812/71969030-f5a32300-3216-11ea-818f-81c726aa5bfc.png">

While it works good, I now see warning messages in `coc-settings.json`:

<img src="https://user-images.githubusercontent.com/674812/71969157-28e5b200-3217-11ea-9063-b055f03ead80.png">

**So**, I think it would be nice to support this options to be specified in `coc-settings.json`.

[1]: https://github.com/vuejs/vetur/blob/ad2490ac55838bda7d18acbf3eaa071ab3ea809d/server/src/modes/vue/index.ts#L9-L13
[2]: https://github.com/vuejs/vetur/blob/ad2490ac55838bda7d18acbf3eaa071ab3ea809d/server/src/modes/vue/index.ts#L21-L23

**Comment by chemzqm** [comment]
Fixed on v1.2.0
