### ISSUE TITLE
tsserver only works in 1 buffer

### ISSUE THREAD

**Issue by Luxed** [neoclide/coc-vetur#24]
OS: Windows 10
Neovim version: 0.5.0-305

Everything else is updated at the latest release version.
For some reason, the first vue buffer I open has typescript support, but if I open a new buffer and hide the old one (I have `set hidden` in my config), the new buffer is always missing the typescript features while everything else works.

I looked at vetur's verbose output of `CocCommand workspace.showOutput` and nothing looks out of the ordinary. The completion request is sent, but I receive nothing.

I tried the same with VSCode, but everything worked perfectly on there.

Any idea on what is happening? What can I do to test it/get more information?
I didn't test with a clean config yet, but I don't think that would be the issue since everything else works (css and html work fine).
Maybe this is a `vue-language-server` issue?

**Comment by chemzqm** [comment]
Checkout verbose output of vetur https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by chemzqm** [comment]
You may need coc-tsserver for javascript and typescript files.

**Comment by Luxed** [comment]
@chemzqm I did some more testing, the issue seem to only happen on this specific project. I will investigate this myself as it is not an open source project and I do not seem to be able to reproduce the issue outside of this specific project :/

**Comment by Luxed** [comment]
@chemzqm I was able to reproduce this issue with a "clean" vim config (only coc.nvim plugin installed).
Here are the steps:
- using vue cli, create new project (I used the `vue ui` command to make it easier)
- manually select features: remove Babel and add Typescript
- once the project is created, open neovim at the top folder of the project
- open the first buffer with `:e src/App.vue`
- tsserver is working fine
- open the second buffer with `:e src/components/HelloWorld.vue`
- tsserver doesn't return anything

<details>
<summary>Vetur verbose's output</summary>
<pre>
<code>
[Trace - 8:42:01 AM] Sending request 'initialize - (0)'.
Params: {
    "processId": 1248,
    "rootPath": "C:\\Users\\cbrunel\\vue\\test",
    "rootUri": "file:///c%3A/Users/cbrunel/vue/test",
    "capabilities": {
        "workspace": {
            "applyEdit": true,
            "workspaceEdit": {
                "documentChanges": true,
                "resourceOperations": [
                    "create",
                    "rename",
                    "delete"
                ],
                "failureHandling": "textOnlyTransactional"
            },
            "didChangeConfiguration": {
                "dynamicRegistration": true
            },
            "didChangeWatchedFiles": {
                "dynamicRegistration": true
            },
            "symbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                }
            },
            "executeCommand": {
                "dynamicRegistration": true
            },
            "configuration": true,
            "workspaceFolders": true
        },
        "textDocument": {
            "publishDiagnostics": {
                "relatedInformation": true
            },
            "synchronization": {
                "dynamicRegistration": true,
                "willSave": true,
                "willSaveWaitUntil": true,
                "didSave": true
            },
            "completion": {
                "dynamicRegistration": true,
                "contextSupport": true,
                "completionItem": {
                    "snippetSupport": true,
                    "commitCharactersSupport": true,
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "deprecatedSupport": true,
                    "preselectSupport": true
                },
                "completionItemKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25
                    ]
                }
            },
            "hover": {
                "dynamicRegistration": true,
                "contentFormat": [
                    "markdown",
                    "plaintext"
                ]
            },
            "signatureHelp": {
                "dynamicRegistration": true,
                "signatureInformation": {
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "parameterInformation": {
                        "labelOffsetSupport": true
                    }
                }
            },
            "definition": {
                "dynamicRegistration": true
            },
            "references": {
                "dynamicRegistration": true
            },
            "documentHighlight": {
                "dynamicRegistration": true
            },
            "documentSymbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                }
            },
            "codeAction": {
                "dynamicRegistration": true,
                "codeActionLiteralSupport": {
                    "codeActionKind": {
                        "valueSet": [
                            "",
                            "quickfix",
                            "refactor",
                            "refactor.extract",
                            "refactor.inline",
                            "refactor.rewrite",
                            "source",
                            "source.organizeImports"
                        ]
                    }
                }
            },
            "codeLens": {
                "dynamicRegistration": true
            },
            "formatting": {
                "dynamicRegistration": true
            },
            "rangeFormatting": {
                "dynamicRegistration": true
            },
            "onTypeFormatting": {
                "dynamicRegistration": true
            },
            "rename": {
                "dynamicRegistration": true,
                "prepareSupport": true
            },
            "documentLink": {
                "dynamicRegistration": true
            },
            "typeDefinition": {
                "dynamicRegistration": true
            },
            "implementation": {
                "dynamicRegistration": true
            },
            "declaration": {
                "dynamicRegistration": true
            },
            "colorProvider": {
                "dynamicRegistration": true
            },
            "foldingRange": {
                "dynamicRegistration": true,
                "rangeLimit": 5000,
                "lineFoldingOnly": true
            }
        }
    },
    "initializationOptions": {
        "config": {
            "vetur": {
                "useWorkspaceDependencies": false,
                "completion": {
                    "autoImport": true,
                    "useScaffoldSnippets": true,
                    "tagCasing": "kebab"
                },
                "validation": {
                    "template": true,
                    "style": true,
                    "script": true
                },
                "format": {
                    "enable": true,
                    "options": {
                        "tabSize": 2,
                        "useTabs": false
                    },
                    "defaultFormatter": {
                        "html": "prettyhtml",
                        "css": "prettier",
                        "postcss": "prettier",
                        "scss": "prettier",
                        "less": "prettier",
                        "stylus": "stylus-supremacy",
                        "js": "prettier",
                        "ts": "prettier"
                    },
                    "defaultFormatterOptions": {
                        "js-beautify-html": {
                            "wrap_attributes": "force-expand-multiline"
                        },
                        "prettyhtml": {
                            "printWidth": 100,
                            "singleQuote": false,
                            "wrapAttributes": false,
                            "sortAttributes": false
                        }
                    },
                    "styleInitialIndent": false,
                    "scriptInitialIndent": false
                },
                "trace": {
                    "server": "verbose"
                },
                "dev": {
                    "logLevel": "INFO"
                },
                "experimental": {
                    "templateInterpolationService": false
                }
            },
            "emmet": {
                "showExpandedAbbreviation": "always",
                "showAbbreviationSuggestions": true,
                "includeLanguages": {},
                "variables": {},
                "syntaxProfiles": {},
                "excludeLanguages": [
                    "markdown"
                ],
                "showSuggestionsAsSnippets": true,
                "preferences": {},
                "optimizeStylesheetParsing": true,
                "priority": 3
            },
            "html": {
                "enable": true,
                "execArgv": [],
                "trace": {
                    "server": "off"
                },
                "filetypes": [
                    "html",
                    "handlebars"
                ],
                "format": {
                    "enable": true,
                    "wrapLineLength": 120,
                    "unformatted": "wbr",
                    "contentUnformatted": "pre,code,textarea",
                    "indentInnerHtml": false,
                    "preserveNewLines": true,
                    "indentHandlebars": false,
                    "endWithNewline": false,
                    "extraLiners": "head, body, /html",
                    "wrapAttributes": "auto"
                },
                "suggest": {
                    "angular1": true,
                    "ionic": true,
                    "html5": true
                },
                "validate": {
                    "scripts": true,
                    "styles": true,
                    "html": true
                }
            },
            "javascript": {
                "showUnused": true,
                "updateImportsOnFileMove": {
                    "enable": true
                },
                "implementationsCodeLens": {
                    "enable": true
                },
                "referencesCodeLens": {
                    "enable": true
                },
                "preferences": {
                    "importModuleSpecifier": "non-relative",
                    "quoteStyle": "auto"
                },
                "validate": {
                    "enable": true
                },
                "suggestionActions": {
                    "enabled": true
                },
                "suggest": {
                    "names": true,
                    "enabled": true,
                    "paths": true,
                    "autoImports": true,
                    "completeFunctionCalls": true
                },
                "format": {
                    "enabled": true,
                    "insertSpaceAfterCommaDelimiter": true,
                    "insertSpaceAfterConstructor": false,
                    "insertSpaceAfterSemicolonInForStatements": true,
                    "insertSpaceBeforeAndAfterBinaryOperators": true,
                    "insertSpaceAfterKeywordsInControlFlowStatements": true,
                    "insertSpaceAfterFunctionKeywordForAnonymousFunctions": true,
                    "insertSpaceBeforeFunctionParenthesis": false,
                    "insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis": false,
                    "insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets": false,
                    "insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces": false,
                    "insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces": false,
                    "insertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces": false,
                    "insertSpaceAfterTypeAssertion": false,
                    "placeOpenBraceOnNewLineForFunctions": false,
                    "placeOpenBraceOnNewLineForControlBlocks": false,
                    "semicolons": "ignore"
                }
            },
            "typescript": {
                "showUnused": true,
                "updateImportsOnFileMove": {
                    "enable": true
                },
                "implementationsCodeLens": {
                    "enable": true
                },
                "referencesCodeLens": {
                    "enable": true
                },
                "preferences": {
                    "importModuleSpecifier": "non-relative",
                    "quoteStyle": "auto"
                },
                "suggestionActions": {
                    "enabled": true
                },
                "validate": {
                    "enable": true
                },
                "suggest": {
                    "enabled": true,
                    "paths": true,
                    "autoImports": true,
                    "completeFunctionCalls": true
                },
                "format": {
                    "enabled": true,
                    "insertSpaceAfterCommaDelimiter": true,
                    "insertSpaceAfterConstructor": false,
                    "insertSpaceAfterSemicolonInForStatements": true,
                    "insertSpaceBeforeAndAfterBinaryOperators": true,
                    "insertSpaceAfterKeywordsInControlFlowStatements": true,
                    "insertSpaceAfterFunctionKeywordForAnonymousFunctions": true,
                    "insertSpaceBeforeFunctionParenthesis": false,
                    "insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis": false,
                    "insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets": false,
                    "insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces": false,
                    "insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces": false,
                    "insertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces": false,
                    "insertSpaceAfterTypeAssertion": false,
                    "placeOpenBraceOnNewLineForFunctions": false,
                    "placeOpenBraceOnNewLineForControlBlocks": false,
                    "semicolons": "ignore"
                }
            },
            "prettier": {
                "formatterPriority": 1,
                "disableLanguages": [
                    "vue"
                ],
                "eslintIntegration": false,
                "tslintIntegration": false,
                "stylelintIntegration": false,
                "requireConfig": false,
                "onlyUseLocalVersion": false,
                "disableSuccessMessage": false,
                "statusItemText": "Prettier",
                "ignorePath": ".prettierignore",
                "printWidth": 80,
                "tabWidth": 2,
                "singleQuote": false,
                "trailingComma": "none",
                "bracketSpacing": true,
                "jsxBracketSameLine": false,
                "jsxSingleQuote": false,
                "htmlWhitespaceSensitivity": "css",
                "endOfLine": "auto",
                "parser": "babylon",
                "semi": true,
                "useTabs": false,
                "proseWrap": "preserve",
                "arrowParens": "avoid"
            },
            "stylusSupremacy": {}
        },
        "globalSnippetDir": "C:\\Users\\cbrunel\\AppData\\Roaming\\Code\\User\\snippets\\vetur"
    },
    "trace": "verbose",
    "workspaceFolders": [
        {
            "uri": "file:///c%3A/Users/cbrunel/vue/test",
            "name": "test"
        }
    ]
}


[Trace - 8:42:03 AM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "Loaded bundled typescript@3.7.4."
}


Loaded bundled typescript@3.7.4.
[Trace - 8:42:03 AM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "Vetur initialized"
}


Vetur initialized
[Trace - 8:42:03 AM] Received response 'initialize - (0)' in 1468ms.
Result: {
    "capabilities": {
        "textDocumentSync": 1,
        "completionProvider": {
            "resolveProvider": true,
            "triggerCharacters": [
                ".",
                ":",
                "<",
                "\"",
                "'",
                "/",
                "@",
                "*"
            ]
        },
        "signatureHelpProvider": {
            "triggerCharacters": [
                "("
            ]
        },
        "documentFormattingProvider": false,
        "hoverProvider": true,
        "documentHighlightProvider": true,
        "documentLinkProvider": {
            "resolveProvider": false
        },
        "documentSymbolProvider": true,
        "definitionProvider": true,
        "referencesProvider": true,
        "codeActionProvider": true,
        "colorProvider": true
    }
}


[Trace - 8:42:03 AM] Sending notification 'initialized'.
Params: {}


[Trace - 8:42:03 AM] Sending notification 'workspace/didChangeConfiguration'.
Params: {
    "settings": {
        "vetur": {
            "useWorkspaceDependencies": false,
            "completion": {
                "autoImport": true,
                "useScaffoldSnippets": true,
                "tagCasing": "kebab"
            },
            "validation": {
                "template": true,
                "style": true,
                "script": true
            },
            "format": {
                "enable": true,
                "options": {
                    "tabSize": 2,
                    "useTabs": false
                },
                "defaultFormatter": {
                    "html": "prettyhtml",
                    "css": "prettier",
                    "postcss": "prettier",
                    "scss": "prettier",
                    "less": "prettier",
                    "stylus": "stylus-supremacy",
                    "js": "prettier",
                    "ts": "prettier"
                },
                "defaultFormatterOptions": {
                    "js-beautify-html": {
                        "wrap_attributes": "force-expand-multiline"
                    },
                    "prettyhtml": {
                        "printWidth": 100,
                        "singleQuote": false,
                        "wrapAttributes": false,
                        "sortAttributes": false
                    }
                },
                "styleInitialIndent": false,
                "scriptInitialIndent": false
            },
            "trace": {
                "server": "verbose"
            },
            "dev": {
                "logLevel": "INFO"
            },
            "experimental": {
                "templateInterpolationService": false
            }
        },
        "emmet": {
            "showExpandedAbbreviation": "always",
            "showAbbreviationSuggestions": true,
            "includeLanguages": {},
            "variables": {},
            "syntaxProfiles": {},
            "excludeLanguages": [
                "markdown"
            ],
            "showSuggestionsAsSnippets": true,
            "preferences": {},
            "optimizeStylesheetParsing": true,
            "priority": 3
        },
        "html": {
            "enable": true,
            "execArgv": [],
            "trace": {
                "server": "off"
            },
            "filetypes": [
                "html",
                "handlebars"
            ],
            "format": {
                "enable": true,
                "wrapLineLength": 120,
                "unformatted": "wbr",
                "contentUnformatted": "pre,code,textarea",
                "indentInnerHtml": false,
                "preserveNewLines": true,
                "indentHandlebars": false,
                "endWithNewline": false,
                "extraLiners": "head, body, /html",
                "wrapAttributes": "auto"
            },
            "suggest": {
                "angular1": true,
                "ionic": true,
                "html5": true
            },
            "validate": {
                "scripts": true,
                "styles": true,
                "html": true
            }
        },
        "javascript": {
            "showUnused": true,
            "updateImportsOnFileMove": {
                "enable": true
            },
            "implementationsCodeLens": {
                "enable": true
            },
            "referencesCodeLens": {
                "enable": true
            },
            "preferences": {
                "importModuleSpecifier": "non-relative",
                "quoteStyle": "auto"
            },
            "validate": {
                "enable": true
            },
            "suggestionActions": {
                "enabled": true
            },
            "suggest": {
                "names": true,
                "enabled": true,
                "paths": true,
                "autoImports": true,
                "completeFunctionCalls": true
            },
            "format": {
                "enabled": true,
                "insertSpaceAfterCommaDelimiter": true,
                "insertSpaceAfterConstructor": false,
                "insertSpaceAfterSemicolonInForStatements": true,
                "insertSpaceBeforeAndAfterBinaryOperators": true,
                "insertSpaceAfterKeywordsInControlFlowStatements": true,
                "insertSpaceAfterFunctionKeywordForAnonymousFunctions": true,
                "insertSpaceBeforeFunctionParenthesis": false,
                "insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis": false,
                "insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets": false,
                "insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces": false,
                "insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces": false,
                "insertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces": false,
                "insertSpaceAfterTypeAssertion": false,
                "placeOpenBraceOnNewLineForFunctions": false,
                "placeOpenBraceOnNewLineForControlBlocks": false,
                "semicolons": "ignore"
            }
        },
        "typescript": {
            "showUnused": true,
            "updateImportsOnFileMove": {
                "enable": true
            },
            "implementationsCodeLens": {
                "enable": true
            },
            "referencesCodeLens": {
                "enable": true
            },
            "preferences": {
                "importModuleSpecifier": "non-relative",
                "quoteStyle": "auto"
            },
            "suggestionActions": {
                "enabled": true
            },
            "validate": {
                "enable": true
            },
            "suggest": {
                "enabled": true,
                "paths": true,
                "autoImports": true,
                "completeFunctionCalls": true
            },
            "format": {
                "enabled": true,
                "insertSpaceAfterCommaDelimiter": true,
                "insertSpaceAfterConstructor": false,
                "insertSpaceAfterSemicolonInForStatements": true,
                "insertSpaceBeforeAndAfterBinaryOperators": true,
                "insertSpaceAfterKeywordsInControlFlowStatements": true,
                "insertSpaceAfterFunctionKeywordForAnonymousFunctions": true,
                "insertSpaceBeforeFunctionParenthesis": false,
                "insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis": false,
                "insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets": false,
                "insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces": false,
                "insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces": false,
                "insertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces": false,
                "insertSpaceAfterTypeAssertion": false,
                "placeOpenBraceOnNewLineForFunctions": false,
                "placeOpenBraceOnNewLineForControlBlocks": false,
                "semicolons": "ignore"
            }
        },
        "prettier": {
            "formatterPriority": 1,
            "disableLanguages": [
                "vue"
            ],
            "eslintIntegration": false,
            "tslintIntegration": false,
            "stylelintIntegration": false,
            "requireConfig": false,
            "onlyUseLocalVersion": false,
            "disableSuccessMessage": false,
            "statusItemText": "Prettier",
            "ignorePath": ".prettierignore",
            "printWidth": 80,
            "tabWidth": 2,
            "singleQuote": false,
            "trailingComma": "none",
            "bracketSpacing": true,
            "jsxBracketSameLine": false,
            "jsxSingleQuote": false,
            "htmlWhitespaceSensitivity": "css",
            "endOfLine": "auto",
            "parser": "babylon",
            "semi": true,
            "useTabs": false,
            "proseWrap": "preserve",
            "arrowParens": "avoid"
        },
        "stylusSupremacy": {}
    }
}


[Trace - 8:42:03 AM] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/Users/cbrunel/vue/test/src/App.vue",
        "languageId": "vue",
        "version": 1,
        "text": "<template>\n  <div id=\"app\">\n    <img alt=\"Vue logo\" src=\"./assets/logo.png\">\n    <HelloWorld msg=\"Welcome to Your Vue.js + TypeScript App\"/>\n  </div>\n</template>\n\n<script lang=\"ts\">\nimport { Component, Vue } from 'vue-property-decorator';\nimport HelloWorld from 'src/components/HelloWorld.vue';\n\n@Component({\n  components: {\n    HelloWorld,\n  },\n})\nexport default class App extends Vue {}\n</script>\n\n<style lang=\"scss\">\n#app {\n  font-family: 'Avenir', Helvetica, Arial, sans-serif;\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n  text-align: center;\n  color: #2c3e50;\n  margin-top: 60px;\n}\n</style>\n"
    }
}


[Trace - 8:42:03 AM] Received request 'client/registerCapability - (0)'.
Params: {
    "registrations": [
        {
            "id": "ebe168d3-8f04-4412-bf6a-eb63f367e187",
            "method": "textDocument/formatting",
            "registerOptions": {
                "documentSelector": [
                    "vue"
                ]
            }
        }
    ]
}


[Trace - 8:42:03 AM] Sending response 'client/registerCapability - (0)'. Processing request took 0ms
No result returned.


[Trace - 8:42:04 AM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///c%3A/Users/cbrunel/vue/test/src/App.vue",
    "diagnostics": []
}


[Trace - 8:42:11 AM] Sending request 'textDocument/hover - (1)'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/Users/cbrunel/vue/test/src/App.vue"
    },
    "position": {
        "line": 8,
        "character": 20
    }
}


[Trace - 8:42:11 AM] Received response 'textDocument/hover - (1)' in 15ms.
Result: {
    "range": {
        "start": {
            "line": 8,
            "character": 20
        },
        "end": {
            "line": 8,
            "character": 23
        }
    },
    "contents": [
        {
            "language": "ts",
            "value": "(alias) interface Vue\n(alias) const Vue: VueConstructor<Vue>\nimport Vue"
        }
    ]
}


[Trace - 8:42:22 AM] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/Users/cbrunel/vue/test/src/components/HelloWorld.vue",
        "languageId": "vue",
        "version": 1,
        "text": "<template>\n  <div class=\"hello\">\n    <h1>{{ msg }}</h1>\n    <p>\n      For a guide and recipes on how to configure / customize this project,<br>\n      check out the\n      <a href=\"https://cli.vuejs.org\" target=\"_blank\" rel=\"noopener\">vue-cli documentation</a>.\n    </p>\n    <h3>Installed CLI Plugins</h3>\n    <ul>\n      <li><a href=\"https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-typescript\" target=\"_blank\" rel=\"noopener\">typescript</a></li>\n    </ul>\n    <h3>Essential Links</h3>\n    <ul>\n      <li><a href=\"https://vuejs.org\" target=\"_blank\" rel=\"noopener\">Core Docs</a></li>\n      <li><a href=\"https://forum.vuejs.org\" target=\"_blank\" rel=\"noopener\">Forum</a></li>\n      <li><a href=\"https://chat.vuejs.org\" target=\"_blank\" rel=\"noopener\">Community Chat</a></li>\n      <li><a href=\"https://twitter.com/vuejs\" target=\"_blank\" rel=\"noopener\">Twitter</a></li>\n      <li><a href=\"https://news.vuejs.org\" target=\"_blank\" rel=\"noopener\">News</a></li>\n    </ul>\n    <h3>Ecosystem</h3>\n    <ul>\n      <li><a href=\"https://router.vuejs.org\" target=\"_blank\" rel=\"noopener\">vue-router</a></li>\n      <li><a href=\"https://vuex.vuejs.org\" target=\"_blank\" rel=\"noopener\">vuex</a></li>\n      <li><a href=\"https://github.com/vuejs/vue-devtools#vue-devtools\" target=\"_blank\" rel=\"noopener\">vue-devtools</a></li>\n      <li><a href=\"https://vue-loader.vuejs.org\" target=\"_blank\" rel=\"noopener\">vue-loader</a></li>\n      <li><a href=\"https://github.com/vuejs/awesome-vue\" target=\"_blank\" rel=\"noopener\">awesome-vue</a></li>\n    </ul>\n  </div>\n</template>\n\n<script lang=\"ts\">\nimport { Component, Prop, Vue } from 'vue-property-decorator';\n\n@Component\nexport default class HelloWorld extends Vue {\n  @Prop() private msg!: string;\n}\n</script>\n\n\n<style scoped lang=\"scss\">\nh3 {\n  margin: 40px 0 0;\n}\nul {\n  list-style-type: none;\n  padding: 0;\n}\nli {\n  display: inline-block;\n  margin: 0 10px;\n}\na {\n  color: #42b983;\n}\n</style>\n"
    }
}


[Trace - 8:42:23 AM] Sending request 'textDocument/documentColor - (2)'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/Users/cbrunel/vue/test/src/components/HelloWorld.vue"
    }
}


[Trace - 8:42:23 AM] Received response 'textDocument/documentColor - (2)' in 16ms.
Result: [
    {
        "color": {
            "red": 0.25882352941176473,
            "green": 0.7254901960784313,
            "blue": 0.5137254901960784,
            "alpha": 1
        },
        "range": {
            "start": {
                "line": 54,
                "character": 9
            },
            "end": {
                "line": 54,
                "character": 16
            }
        }
    }
]


[Trace - 8:42:23 AM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///c%3A/Users/cbrunel/vue/test/src/components/HelloWorld.vue",
    "diagnostics": []
}


[Trace - 8:42:33 AM] Sending request 'textDocument/hover - (3)'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/Users/cbrunel/vue/test/src/components/HelloWorld.vue"
    },
    "position": {
        "line": 32,
        "character": 26
    }
}


[Trace - 8:42:33 AM] Received response 'textDocument/hover - (3)' in 0ms.
Result: {
    "contents": []
}
</code>
</pre>
</details>
