### ISSUE TITLE
Possible to include bootstrapvue intellisense autocompletion?

### ISSUE THREAD

**Issue by warrence** [neoclide/coc-vetur#27]
Hi, i found that bootstrap vue have some json file for vscode+vetur, im wondering if it works with coc-vetur too?

Please refer to the link below
https://bootstrap-vue.js.org/docs/#vs-code--vetur

**Comment by chemzqm** [comment]
I don't know it's feature of vetur server or vscode extenison of vetur, you need check their doc.

**Comment by warrence** [comment]
It works only if vetur server?

**Comment by warrence** [comment]
Further research i found that vetur are using framework which should be already supported if we are using bootstrap-vue 2.1 or above, correctly me if im wrong, because im not sure whether coc-vetur should work the same as vetur, as vetur page are offering to install vetur as coc extension too. 

Any help would be very very appreciated as i'm a heavy vuejs developer, coc has been helping me a big big hand in autocompletion for laravel and vue, and this bootstrap vue is gonna make it even more perfect, winning over phpstorm (has been using for few years) which i migrate over.

**Comment by last-partizan** [comment]
![image](https://user-images.githubusercontent.com/301015/95650378-fccfc800-0aeb-11eb-8279-938fbc217fb0.png)
![image](https://user-images.githubusercontent.com/301015/95650382-0f4a0180-0aec-11eb-87e5-7b51d1a267c6.png)

@warrence looks like it's already working.

**Comment by chemzqm** [comment]
Should be fixed by upgrade vls.
