### ISSUE TITLE
Strange menu display when using ale

### ISSUE THREAD

**Issue by npearson72** [neoclide/coc-vetur#3]
When using https://github.com/w0rp/ale the auto complete menu shifts and displays a duplicate.

See animated gif:

![kapture 2019-01-08 at 23 34 22](https://user-images.githubusercontent.com/1323414/50862343-14709e80-13a4-11e9-8313-78923e9386d4.gif)

**Comment by chemzqm** [comment]
It should be bug of neovim or the terminal you're using.
You can add `set signcolumn=yes` to avoid column change.
Also use `set shortmess+=c` to avoid the messages from vim on complete item change.

**Comment by npearson72** [comment]
Thanks, that helps!

**Comment by npearson72** [comment]
@chemzqm I'm wondering if you know... it seems vetur isn't a very good language server?  tsserver seems to work much better.

Is this true or do I have something set incorrectly?

For example, in my vue file if I have props that point to an array, I would think the language server would understand this and offer methods for array (ex: map, slice, etc.). But it doesn't.

**Comment by chemzqm** [comment]
Vetur use tsserver for javascript code, I think it's just tsserver doesn't understand props of vue well.
