### ISSUE TITLE
Can't Build from source

### ISSUE THREAD

**Issue by HassanZahin** [neoclide/coc-vetur#31]
when tried to build with:
zahin@zahin-desktop:node_modules/coc-vetur ‹master*›$ yarn --registry "https://registry.npmjs.org"
yarn install v1.22.4
warning ../../package.json: No license field
[1/5] Validating package.json...
warning coc-vetur@1.1.10: The engine "coc" appears to be invalid.
[2/5] Resolving packages...
success Already up-to-date.
$ npx npm-run-all clean build
npx: installed 60 in 14.362s
yarn run v1.22.4
warning ../../package.json: No license field
warning coc-vetur@1.1.10: The engine "coc" appears to be invalid.
$ rimraf lib
Done in 0.45s.
yarn run v1.22.4
warning ../../package.json: No license field
warning coc-vetur@1.1.10: The engine "coc" appears to be invalid.
$ webpack
Hash: 54ccb7d0b6e0afe91681
Version: webpack 4.43.0
Time: 135ms
Built at: 04/23/2020 6:08:58 PM
   Asset      Size  Chunks             Chunk Names
index.js  4.08 KiB       0  [emitted]  main
Entrypoint main = index.js
[0] ./src/index.ts 462 bytes {0} [built] [failed] [1 error]

ERROR in ./src/index.ts 8:8
Module parse failed: Unexpected token (8:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import path from 'path'
| import os from 'os'
> declare var __webpack_require__: any
| declare var __non_webpack_require__: any
| const requireFunc = typeof __webpack_require__ === 'function' ? __non_webpack_require__ : require
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build" exited with 2.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by chemzqm** [comment]
You have to use `yarn install --production --ignore-scripts` for package from npm.js

**Comment by HassanZahin** [comment]
seems like its a problem with ts-loader.

`yarn global v1.22.4
warning ../../package.json: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > ts-loader@7.0.1" has unmet peer dependency "typescript@*".
[4/4] Building fresh packages...

warning "ts-loader@7.0.1" has no binaries
Done in 3.48s.
`
