### ISSUE TITLE
coc-vetur not working: vls keeps stopping

### ISSUE THREAD

**Issue by ZHAJOR** [neoclide/coc-vetur#33]
Hi,

OS: Ubuntu 18
Node: v13

Error (:CocOpenLog):
```
2020-05-14T01:50:05.279 INFO (pid:20661) [language-client-index] - vetur started with 20719
   17 2020-05-14T01:50:05.813 INFO (pid:20661) [services] - Vetur Language Server state change: starting => running
   18 2020-05-14T01:50:06.033 INFO (pid:20661) [services] - Vetur Language Server state change: running => stopped
   19 2020-05-14T01:50:06.033 INFO (pid:20661) [services] - Vetur Language Server state change: stopped => starting
....
```

I freshly installed neovim, then coc.nvim, then multiple coc extensions, but with coc-vetur I'm facing a problem. When I open a .vue file nothing is working, except a very basic completion on the current file. I checked the coc's logs and I discovered that vls was stopping again and again (5 times max).

I already tried to install vls globally and edit the path in the coc configuration but it's not working, even putting a wrong path isn't triggering anything, still having this start/stop thing.

Do you have any idea of what could be happening?

Thank you

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by ZHAJOR** [comment]
Thanks for the quick answer, I'm going to start debugging.

Looks like it's a missing dependency:
`Error: Failed to load plugin 'vue' declared in 'CLIOptions': Cannot find module 'eslint-plugin-vue'`

Before going further, we agree that I shouldn't need to install anything on the side?

**Comment by chemzqm** [comment]
Looks like you have to install eslint-plugin-vue eslint to your devDependencies

**Comment by ZHAJOR** [comment]
You're right:
`npm install eslint eslint-plugin-vue --save-dev`
I was testing on a fresh project and these were missing.

Anyway, thanks again!
