### ISSUE TITLE
Format option behaves differently from coc-prettier

### ISSUE THREAD

**Issue by iagosrodrigues** [neoclide/coc-vetur#35]
When using the `:call CocActionAsync('format')` the output differs from the `:PrettierAsync`. These two use different configurations?

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by iagosrodrigues** [comment]
Yeah, the problem is that a new Vue project doesn't have a prettier configuration file.

The issue can be closed.
