### ISSUE TITLE
Go to file doesn't work when I use alias import module

### ISSUE THREAD

**Issue by vinibispo** [neoclide/coc-vetur#36]
---
#### When I use go to file in vue file with alias import module, that doesn't work
---
### Example
```vue
import Home from '@/pages/Home'
```
That returns
```
E447: Can't find file "/pages/Home" in path
```
---
#### This is my jsconfig.json
```json
{
    "compilerOptions": {
      "baseUrl": ".",
      "paths": {
        "@/*": [
          "src/*"
        ]   
      }   
    }
  }
```

**Comment by pr0xyMity** [comment]
Same problem :(

**Comment by vinibispo** [comment]
My solution for that was to use go to definition instead of go to file, because go to file isn't working

**Comment by chemzqm** [comment]
Issue of vim, not coc.nvim related.
