### ISSUE TITLE
Warning accessing non-existant property 

### ISSUE THREAD

**Issue by AdamBD** [neoclide/coc-vetur#37]
Hi! 

I am running into this output each time coc-vetur loads:

## Output channel: vetur
[Error  - 6:39:45 PM] (node:6835) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
[Error  - 6:39:45 PM] (node:6835) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
[Error  - 6:39:45 PM] (node:6835) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
[Error  - 6:39:45 PM] (node:6835) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
[Error  - 6:39:45 PM] (node:6835) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
[Error  - 6:39:45 PM] (node:6835) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
Loaded bundled typescript@3.9.5.
Vetur initialized

**Comment by chemzqm** [comment]
It's problem of your vls, we can't help.
