### ISSUE TITLE
Extra spacing before closing tabs when using snippets

### ISSUE THREAD

**Issue by saeedahadian** [neoclide/coc-vetur#38]
Hi everyone,
I use Vim 8 and installed coc-vetur successfully. The problem is that when I use vetur snippets, there is an extra amount of space before closing tags that don't seem right.

![spacing-before-format](https://user-images.githubusercontent.com/44898249/84751757-2bbcae00-afd2-11ea-8407-40cc122f187d.png)

Even when I use _:Format_ command to format my code, things get worse.

![spacing-after-format](https://user-images.githubusercontent.com/44898249/84751887-5575d500-afd2-11ea-92c8-779247d4a8f4.png)

I checked out the configurations but didn't find anything that might be related to this issue.

**Comment by chemzqm** [comment]
Try minimal vimrc.

**Comment by saeedahadian** [comment]
Just in case somebody had the same problem, I managed to fix it by changing the shortcut for expanding snippets from tab to C-l as is mentioned in coc-snippets configuration. Seems hitting tab was creating a tab space before each line.

**Comment by chemzqm** [comment]
@saeedahadian it's because you have broken key-mapping of `<tab>`
