### ISSUE TITLE
The "vetur" server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by ArkjuniorK** [neoclide/coc-vetur#39]
Vetur always send an error when open vue file.
What was actually happen? I've tried to uninstall the coc-vetur and reinstall it but it always send me the same error.

![Screenshot from 2020-06-27 19-18-14](https://user-images.githubusercontent.com/58880821/85920970-face5a00-b8aa-11ea-9779-4867c06d2982.png)

**Comment by chemzqm** [comment]
Try upgrade coc-vetur.

**Comment by ArkjuniorK** [comment]
How to upgrade coc-vetur? Is use the `:CocInstall coc-vetur` command?

**Comment by ArkjuniorK** [comment]
Upgrade from version `1.1.10` to `1.1.11` solved the problem. Thanks

**Comment by chanwutk** [comment]
I have the same problem and I am using version 1.1.11
What vim version are you using and what os are you using?

**Comment by ArkjuniorK** [comment]
I'm using NeoVim and Pop Os... 
Try to open the folder/file in the root directory, it works for me.

**Comment by chanwutk** [comment]
Thank you!
I actually solved it :)
I `npm i eslint eslint-plugin-vue -D` in my project directory.
