### ISSUE TITLE
cannot make coc-vetur working

### ISSUE THREAD

**Issue by 0x8f701** [neoclide/coc-vetur#40]
I installed coc-vetur by running:
```
:CocInstall coc-vetur
```
Then I installed dev dependencies in my vue project
```
yarn add eslint eslint-plugin-vue --dev
```
BTW, I installed vim-vue also, I can see the filtype is correct.

Then I tried to open  a vue file, it still gives me the message:

```
Parsing error: unexpected token <
```

**Comment by 0x8f701** [comment]
vim version: `8.2`
node version: `10.15.3`

vimrc:

https://github.com/GopherJ/cfg/blob/master/coc/.vimrc

**Comment by chemzqm** [comment]
Try upgrade coc-vetur.
