### ISSUE TITLE
How do I get this to work?

### ISSUE THREAD

**Issue by stobbsm** [neoclide/coc-vetur#42]
Installed coc-vetur in neovim, fedora 32, also installed coc-eslint, coc-json, coc-tsserver, coc-prettier and coc-css

I installed, separately, vls (as vue-language-server isn't maintained), but vetur crashes on start.

Can't access the vetur channel to get specific diagnostic information, but if you need something, I think I can get the full coc log for you.

**Comment by chemzqm** [comment]
Please upgrade coc-vetur
