### ISSUE TITLE
Outline view isn't retrieving all of the symbols

### ISSUE THREAD

**Issue by Steadyx** [neoclide/coc-vetur#43]
### Problem
*Hey there, I love the plug-in. Really helpful. It works great except for one minor issue, I've noticed that I can't access a lot of the symbols compared to something like vs-codes outline view. For instance, when I inspect the symbols in outline view I get all of the class names and everything in the template but for some reason, it seems to completely skip everything in the script tag except for the default object. Here are some screenshots to further explain what I mean. 

### Examples
Some test code in Vue

<img width="565" alt="Screenshot 2020-06-30 at 15 40 48" src="https://user-images.githubusercontent.com/13971238/86140549-e081bf80-bae8-11ea-90ce-105e20d38543.png">

The symbols in the outline view in vim:

<img width="273" alt="Screenshot 2020-06-30 at 15 41 22" src="https://user-images.githubusercontent.com/13971238/86140691-06a75f80-bae9-11ea-9fa9-e17cbc1fe559.png">
<img width="419" alt="Screenshot 2020-06-30 at 15 41 53" src="https://user-images.githubusercontent.com/13971238/86140712-0dce6d80-bae9-11ea-9a00-9d9cdd82def9.png">

The outline view with symbols in vs code looks further into the script methods and properties

<img width="271" alt="Screenshot 2020-06-30 at 15 44 02" src="https://user-images.githubusercontent.com/13971238/86140901-4c642800-bae9-11ea-88c5-f8ad925888b9.png">

If you need any more information or if I wasn't descriptive enough let me know

**Comment by chemzqm** [comment]
It's what returned from vetur, could be different version of vetur of configuration problem.

**Comment by Steadyx** [comment]
Got it working cheers, it was driving me mad. I installed vls globally and gave the vetur.dev.vlsPath the path from the node_modules but for some reason that still wasn't working. I figured I'd try using the server from vs-code and it works like a charm now.

**Comment by chemzqm** [comment]
So they didn't made module on npm uptodate
