### ISSUE TITLE
Vue cannot find methods that are async

### ISSUE THREAD

**Issue by lunchboxsushi** [neoclide/coc-vetur#46]
This plugin works right out of the box the only things that I'm not sure if there's some configuration that I need to do or if it's the limitation of the underlying protocol. But if I have an `async` method I cannot find the definition using find references or go to definition in a `.vue` file.

for instance I have the following 
![image](https://user-images.githubusercontent.com/10443153/90437585-a2dcf400-e0a0-11ea-8170-b409b8620385.png)

None of the methods that have `async` will be found. Everything else working as expected simply. The error I get is
>  **[coc.nvim] Definition not found.**

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
