### ISSUE TITLE
1.1.12 No longer shows LS snippets?

### ISSUE THREAD

**Issue by npearson72** [neoclide/coc-vetur#47]
After upgrading from 1.1.11, my LS Vue snippets no longer appear in the omnicompletion menu.

**Comment by suciptoid** [comment]
Facing same issue here 

Version: 1.1.12

**Comment by joaopms** [comment]
Seems like a problem with vls (see https://github.com/vuejs/vetur/issues/2148).

To fix this, specify a custom vls path that uses vls >= 0.5.0. For me, it's as simple as `npm install -g vls` and then setting `vetur.dev.vlsPath` (in `:CocConfig`) to `/usr/lib/node_modules/vls` (you need to specify the whole folder, not the binary). You can also install it somewhere else, just make sure you're pointing `vetur.dev.vlsPath` to the correct directory.

**Comment by suciptoid** [comment]
Thanks @joaopms, btw the configuration key is "vetur.dev.vlsPath"

**Comment by joaopms** [comment]
> Thanks @joaopms, btw the configuration key is "vetur.dev.vlsPath"

I've updated my comment, thank you!
