### ISSUE TITLE
vue import go to definition fail

### ISSUE THREAD

**Issue by timsofteng** [neoclide/coc-vetur#48]
Hello.
I recently installed coc and coc-vetur.
But I faced a problem with `go to definiton feature`. It does not work in my project with imports like this:
`import withForm from "@/mixins/withForm";`

Can you help me with it? 
Thanks

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

Configure jsconfig.json or tsconfig.json might help.
