### ISSUE TITLE
i install coc-vetur, what should i do can let it work

### ISSUE THREAD

**Issue by likelxl** [neoclide/coc-vetur#5]
![default](https://user-images.githubusercontent.com/12811070/51081287-0a91c700-1727-11e9-97d1-52af3848312d.png)
![default](https://user-images.githubusercontent.com/12811070/51081270-a7079980-1726-11e9-84ff-3f742a6bd093.png)
![default](https://user-images.githubusercontent.com/12811070/51081285-eb933500-1726-11e9-8cd4-baf16acfb05c.png)
![default](https://user-images.githubusercontent.com/12811070/51081470-f6e85f80-172a-11e9-95a3-c745e956b33f.png)

**Comment by chemzqm** [comment]
You need to install a filetype plugin, like https://github.com/posva/vim-vue

**Comment by likelxl** [comment]
> You need to install a filetype plugin, like https://github.com/posva/vim-vue

[coc.nvim] Error: Cannot find module 'postcss-html/extract' 1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in '
require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using proc
ess.cwd() or process.execPath.     at Function.Module._resolveFilename (module.js:534:15)     at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1280:46)     at Function.Module._lo
ad (module.js:464:25)     at Module.require (module.js:577:17)     at Module.require (pkg/prelude/bootstrap.js:1159:31)     at require (internal/module.js:11:18)     at rules.filter.map.rule 
(/home/erge/.config/coc/extensions/node_modules/postcss-syntax/processor.js:9:19)     at Array.map (<anonymous>)     at processor (/home/erge/.config/coc/extensions/node_modules/postcss-synta
x/processor.js:6:54)     at Object.parse (/home/erge/.config/coc/extensions/node_modules/postcss-syntax/parse.js:18:9)

**Comment by chemzqm** [comment]
Try `:CocUpdate`
