### ISSUE TITLE
Issue with Emmet completion

### ISSUE THREAD

**Issue by domi91c** [neoclide/coc-vetur#52]
This plugin is almost perfect, but when I try to use it for emmet completions, the completion menu displaying emmet options will appear and then disappear on each additional keypress. 

I'm not too sure how to debug this. I thought I'd just see if any one has experience anything similar. I've also tried installing the coc-emmet plugin along with coc-vetur, it didn't seem to make a difference with this bug. 

![coc-emmet-issue-demo](https://user-images.githubusercontent.com/5838941/93946718-ff6aa900-fd07-11ea-89fe-e83263c8f9e0.gif)

**Comment by chemzqm** [comment]
Emmet items would have empty word, use `<C-y>` to confirm completion or `<C-e>` to cancel.

**Comment by domi91c** [comment]
`<C-y>` triggers the emmet completion if the popup is open, but if it's not open, it doesn't. So the issue is still that the popup menu closes on each keypress. I'm not sure what you mean by "Emmet items would have empty word".

Thanks for the fast response and for your incredible efforts on these tools.

**Comment by chemzqm** [comment]
> <C-y> triggers the emmet completion if the popup is open, but if it's not open, it doesn't

It's expected, this extension does completion only, you can remap your `<C-y>`
