### ISSUE TITLE
GotoDefinition support?

### ISSUE THREAD

**Issue by AdamBD** [neoclide/coc-vetur#55]
Hi team,

awesome work, this plugin is great!

One thing I notice is there is not available jump to definition with functions defined in .vue files or in .js files for that matter that are in a vue project directory.

Is there a way to get support for this?

**Comment by Artawower** [comment]
I also have some problem, but if i make new project it work, i think its problem about jsonconfig.json (but i don't know how fix it)

**Comment by chemzqm** [comment]
I don't know, you may need jsconfig.json, or ask vetur developer for help.

**Comment by AdamBD** [comment]
what is jsconfig.json?

**Comment by chemzqm** [comment]
Google helps

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
