### ISSUE TITLE
ventur service not able to start on fresh WSL install

### ISSUE THREAD

**Issue by johannboehme** [neoclide/coc-vetur#57]
the coc ventur service is unable to startup.
It stays in state "starting"
![image](https://user-images.githubusercontent.com/58803954/99229284-18ff0d00-27ee-11eb-83c7-a666e3d6d7ca.png)

Environment:
Fresh Debian WSL Instance with node.js 15, lastest VIM+coc.nvim+coc-vetur plugin.
eslint and eslint-plugin-vue are installed in the vue project.

Install did not report any errors:
![image](https://user-images.githubusercontent.com/58803954/99230270-6d56bc80-27ef-11eb-85b2-074c7633f710.png)

CocInfo log:
![image](https://user-images.githubusercontent.com/58803954/99229875-e1449500-27ee-11eb-95e7-a9605bec6729.png)

I reproduced this behavior on several newly installed instances.
Other coc implementations (e.g. coc-html, coc-java) work as intended.

Any input how to analyze this further would be very appreciated.

BR,
J.Boehme

**Comment by chemzqm** [comment]
Seems problem with vls  https://www.npmjs.com/package/vls

Checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by johannboehme** [comment]
Thanks for the fast response and for sending me in the right direction!
(Follow up issue: https://github.com/vuejs/vetur/issues/2475)
