### ISSUE TITLE
Cannot add filetypes

### ISSUE THREAD

**Issue by jtumano** [neoclide/coc-vetur#6]
I am trying to set vetur to work in .ts files. Readme said: 
`vetur.filetypes filetypes for vetur, default ['vue']`

But when I'm adding this property into coc-settings.json it doesn't work. 

Also it is not shown in coc-settings.json autocomplete and it has error when adding manually: 

![Screenshot from 2019-04-26 17-13-43](https://user-images.githubusercontent.com/14204232/56813928-b11d5600-6846-11e9-8ab5-a90fc431f85b.png)

**Comment by chemzqm** [comment]
It's not supported, I've fixed the documentation.
The server can't work with other filetypes.
