### ISSUE TITLE
安装后不起作用

### ISSUE THREAD

**Issue by tonnyone** [neoclide/coc-vetur#62]
配置文件显示这样：
![image](https://user-images.githubusercontent.com/6793701/106385233-2c437100-640a-11eb-86c6-a4a8646cd925.png)

用一下命令看，什么也没有输出：

:CocCommand workspace.showOutput vetur.

**Comment by tonnyone** [comment]
刚开始用这种方式安装的
 Plug 'neoclide/coc-vetur', {'do': 'yarn install --frozen-lockfile'}

发现有时候加载不了部分extension:

```
 Plug 'neoclide/coc-vetur', {'do': 'yarn install --frozen-lockfile'}
 Plug 'neoclide/coc-prettier', {'do': 'yarn install --frozen-lockfile'}

```
换成这种方式就好了

```
let g:coc_global_extensions = [
 \    'coc-html', 
 \    'coc-css', 
 \    'coc-tsserver', 
 \    'coc-json', 
 \    'coc-snippets', 
 \    'coc-highlight', 
 \    'coc-pairs', 
 \    'coc-vetur', 
 \    'coc-prettier' 
 \]
```

**Comment by yaegassy** [comment]
@tonnyone It seems that this [commit](https://github.com/neoclide/coc-vetur/commit/d5fd1ea31da284ea7a4f05f0c5766180ebd58547#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L18) removes `prepare`.

Try `yarn install --frozen-lockfile && yarn build`.

```vim
Plug 'neoclide/coc-vetur', {'do': 'yarn install --frozen-lockfile && yarn build'}
```
