### ISSUE TITLE
Eslint disable comment doesn't stop the linting errors

### ISSUE THREAD

**Issue by ashishbinu** [neoclide/coc-vetur#65]
In visual studio code putting this`/* eslint-disable no-unused-vars */` comment on the top the file stops all the linting error from showing related to unused vars in the file. But using `coc-vetur` doesn't do that for neovim .I have posted the screenshot below:

![image](https://user-images.githubusercontent.com/56691622/110217342-78864300-7ed9-11eb-94cb-2456a2585ae7.png)
Is there any way to fix it?

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by chemzqm** [comment]
Latest coc.nvim can't work with neovim 0.3

**Comment by yaegassy** [comment]
@ashishbinu Does your VSCode really suppress `/* eslint-disable no-unused-vars */` if you put it at the top of the file?

In my environment, even in the case of VSCode's `vetur` extension, diagnostic message is not suppressed even if there is `/* eslint-disable no-unused-vars */` at the top of the file.

<img width="1245" alt="coc-vetur-issue-65" src="https://user-images.githubusercontent.com/188642/110242680-80f28280-7f9a-11eb-96f1-a89beb3fb557.png">

I think writing `/* eslint-disable no-unused-vars */` in the `<script>` block is the right way to go.

```vue
<template>
// ... snip
</template>

<script>
/* eslint-disable no-unused-vars */
// ... snip
</script>

<style>
// ... snip
</style>
```

**Comment by ashishbinu** [comment]
> @ashishbinu Does your VSCode really suppress /* eslint-disable no-unused-vars */ if you put it at the top of the file?

I just checked .I am sorry I might have misremembered vs-code doing it. 

> I think writing /* eslint-disable no-unused-vars */ in the <script> block is the right way to go.

Yeah, this works .But on that note shouldn't the `code-action` put that comment inside the `<script>` tag automatically instead of putting it at the top of the file.
![image](https://user-images.githubusercontent.com/56691622/110243259-9f975000-7f7f-11eb-881a-3caec6d5b284.png)
This puts the comment at the top of the file.

**Comment by yaegassy** [comment]
I think the code action problem is a "bug" in `vls` itself, and the same behavior is seen in VSCode. Please report the issue to vetur. https://github.com/vuejs/vetur/issues

**Comment by yaegassy** [comment]
@ashishbinu I did some more checking in my environment, and it seems that the `eslint` extension is emitting the code-action.

**Comment by ashishbinu** [comment]
@yaegassy Should I open this issue in `eslint` repository?

**Comment by chemzqm** [comment]
It's issue of vls.
