### ISSUE TITLE
Support Vue3

### ISSUE THREAD

**Issue by wgxh** [neoclide/coc-vetur#69]
Hello author!
Recently, I wrote some code with Vue3,
But, This plugin is not work.
Please add Vue3 support to this plugin! Thanks!

**Comment by chemzqm** [comment]
Send your feature request to https://www.npmjs.com/package/vls

**Comment by wgxh** [comment]
> Send your feature request to https://www.npmjs.com/package/vls

Thanks! I getting it!

**Comment by yaegassy** [comment]
@wgxh What does it mean that Vue3 is not supported?

The `<script setup>` is also available without any problems and no errors.

Install the `vetur` extension in "VSCode" and see if there is any difference from `coc-vetur`.

**Comment by wgxh** [comment]
> @wgxh What does it mean that Vue3 is not supported?
> 
> The is also available without any problems and no errors.`<script setup>`
> 
> Install the extension in "VSCode" and see if there is any difference from .`vetur``coc-vetur`

Vue3 is not fully supported, I should say so.
Some new feature is not supported, like `<script setup>`,`css v-bind()`
