### ISSUE TITLE
Cannot get linting and formating to work

### ISSUE THREAD

**Issue by ladevieq** [neoclide/coc-vetur#7]
I installed coc-vetur and coc-eslint extensions and vim-vue but i can't get neither linting or fixing to work on vue files, however completion is working correctly.

My coc-settins.json
``` JSON
{
    "eslint.packageManager": "npm",
    "eslint.validate": [
        {
            "language": "javascript",
            "autoFix": true
        },
        {
            "language": "vue",
            "autoFix": true
        },
    ],
    "eslint.autoFixOnSave": true
}
```

My .eslintrc.json
``` JSON
{
    "root": true,
    "extends": [
        "airbnb-base",
        "plugin:vue/recommended"
    ],
}
```

I tried the same stufff with vscode and errors are shown.

**Comment by chemzqm** [comment]
coc-eslint doesn't work with vue filetype by default, please use output channel https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by ladevieq** [comment]
Here is vls communications :

![image](https://user-images.githubusercontent.com/7492041/58786008-f7ed3100-85e6-11e9-89f1-ce854a2b9c5d.png)

What to do with the logs ?

Because when opening a `vue` file, only vetur extension startup.

Even if eslint is started it doesn't  work with vue files as you said, but i don't have any clues about the origin of the issue.

Here is the full vls output :

[vetur.log](https://github.com/neoclide/coc-vetur/files/3247758/vetur.log)

**Comment by chemzqm** [comment]
Checkout https://github.com/neoclide/coc-eslint/blob/master/Readme.md#L39

**Comment by ladevieq** [comment]
Ok so the problem came from this part of my coc-settings.json

``` JSON
"eslint.validate": [
   {
        "language": "javascript",
        "autoFix": true
    },
    {
        "language": "vue",
        "autoFix": true
    },
],
```

The correct way to do this is

``` JSON
"eslint.filetypes": [
   "javascript",
   "vue"
],
```

This part of the README wasn't clear for me.

Thanks for help. 👍

**Comment by fourcube** [comment]
@ladevieq Does formatting HTML inside `<template>...</template>` work for you?

**Comment by ladevieq** [comment]
@fourcube Yes it works for me.

Here is my config :
```json
    "eslint.autoFixOnSave": true,
    "eslint.filetypes": [
        "javascript",
        "vue"
    ],
```

Maybe your filetype is wrong or something like that.

**Comment by ladevieq** [comment]
@fourcube Is the formating of css / scss / less working for you ?

Can figure out why it doesn't work.
