### ISSUE TITLE
Vetur is unable to show type declaration for "this" in pages dirrectory.

### ISSUE THREAD

**Issue by raveltan** [neoclide/coc-vetur#72]
Vetur will report that types of properties inside of this keyword as any on pages/ (not including subdirs).
![Screenshot from 2021-06-04 00-17-35](https://user-images.githubusercontent.com/48407670/120686073-cc99c700-c4ca-11eb-9bcc-bac8c93196ff.png)
![Screenshot from 2021-06-04 00-17-08](https://user-images.githubusercontent.com/48407670/120686082-d02d4e00-c4ca-11eb-9b76-4369c502f8a9.png)

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by raveltan** [comment]
@chemzqm 
really sorry, i sent the wrong screenshot.
the correct one is this one,

![Screenshot from 2021-06-04 08-31-48](https://user-images.githubusercontent.com/48407670/120732450-887ce580-c50f-11eb-800a-172d6043a0dc.png)
![Screenshot from 2021-06-04 08-31-40](https://user-images.githubusercontent.com/48407670/120732457-8adf3f80-c50f-11eb-82b1-4b163d5f498b.png)

Are these also a problem about my language server?
