### ISSUE TITLE
Getting typescript warnings despite using javascript

### ISSUE THREAD

**Issue by MuizU** [neoclide/coc-vetur#74]
I am using coc-vetur with nvim 0.5. I am getting tsserver warnings and errors despite selecting javascript. Is there anyway I can cancel this out?
![image](https://user-images.githubusercontent.com/35157872/125398306-c6054600-e3cc-11eb-99a6-be6f79c1a794.png)

**Comment by chemzqm** [comment]
Check configuration from vetur

**Comment by chemzqm** [comment]
Check configuration from vetur
